In [2]:
import numpy as np

In [7]:
a1 = np.array([1,2,3,4,5])
a2= np.array([6,7,8,9,10])
a2

array([ 6,  7,  8,  9, 10])

In [8]:
a1 + a2

array([ 7,  9, 11, 13, 15])

In [9]:
a1 -a2

array([-5, -5, -5, -5, -5])

In [10]:
a1 * a2

array([ 6, 14, 24, 36, 50])

In [12]:
a2/ a1

array([6.        , 3.5       , 2.66666667, 2.25      , 2.        ])

In [13]:
a2 %a1

array([0, 1, 2, 1, 0])

In [14]:
l = [10,20,30,40]
arr= np.array(l)
arr

array([10, 20, 30, 40])

In [15]:
arr + 10

array([20, 30, 40, 50])

In [16]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [18]:
arr1 = arr + 2
arr1

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [21]:
arr1 = np.arange(1,31).reshape(6,5)
arr1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [22]:
arr1 + 10

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40]])

In [23]:
arr = np.arange(1,21)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [27]:
slice =arr[:5]
slice * 10

array([10, 20, 30, 40, 50])

In [29]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [31]:
arr[0] = 11
arr

array([11,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [32]:
A = np.array([[1,2,3], [4,5,6]])
B = np.array([[7,8,9], [10,11,12]])
A

array([[1, 2, 3],
       [4, 5, 6]])

In [33]:
B

array([[ 7,  8,  9],
       [10, 11, 12]])

In [40]:
A @ B.T

array([[ 50,  68],
       [122, 167]])

In [42]:
a = np.array([1,2,3,4,5])
b= np.array([6,7,8,9,10])
a

array([1, 2, 3, 4, 5])

In [45]:
np.vstack((a,b))

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [46]:
np.hstack((a,b))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [48]:
np.column_stack((a,b))

array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]])

In [3]:
import numpy as np

In [4]:
arr = np.arange(1,17).reshape(4,4)
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [17]:
np.hsplit(arr,2)


[array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14]]),
 array([[ 3,  4],
        [ 7,  8],
        [11, 12],
        [15, 16]])]

In [18]:
np.vsplit(arr,2)

[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12],
        [13, 14, 15, 16]])]