In [1]:
import numpy as np

In [5]:
arr= np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [12]:
a= [1,2,3.5]
a

[1, 2, 3.5]

In [13]:
np.array(a)

array([1. , 2. , 3.5])

In [14]:
l= [[1,2,3], [4,5,6], [7,8,9]]
np.array(l)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
arr= np.arange(1,11,2)
arr

array([1, 3, 5, 7, 9])

In [25]:
arr = np.zeros((6,6))
arr

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [31]:
arr= np.ones((4,6))
arr

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [34]:
arr =np.linspace(1,5,9)
arr

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [35]:
arr=np.random.rand(5)
arr

array([0.94395067, 0.46964011, 0.31722346, 0.42667047, 0.31867422])

In [43]:
arr = np.random.randn(6)
arr

array([-0.64801753, -0.20685811,  2.11658587,  1.72446914, -1.77375117,
        1.06955144])

In [60]:
arr=np.random.randint(10,20,9)
arr

array([19, 17, 15, 17, 16, 19, 12, 15, 15], dtype=int32)

In [61]:
arr= np.ones((4,6))
arr

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [62]:
arr.shape

(4, 6)

In [68]:
arr= np.array([[1,2,3], [4,5,6], [7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [69]:
arr.shape

(3, 3)

In [70]:
arr.size

9

In [72]:
arr.dtype

dtype('int64')

In [73]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [74]:
arr.min()

np.int64(1)

In [75]:
arr.max()

np.int64(9)

In [76]:
arr.sum()

np.int64(45)

In [77]:
np.sum(arr,axis = 1)

array([ 6, 15, 24])

In [78]:
np.sum(arr,axis =0)

array([12, 15, 18])

In [82]:
arr.mean()


np.float64(5.0)

In [83]:
arr.sum()

np.int64(45)

In [84]:
arr.std()

np.float64(2.581988897471611)

In [85]:
arr.argmax()

np.int64(8)

In [88]:
arr = np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [90]:
arr.reshape(6,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])