In [1]:
import numpy as np

In [5]:
arr= np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [6]:
arr[6]

np.int64(17)

In [7]:
arr[-1]

np.int64(20)

In [10]:
arr[: :-1]

array([20, 19, 18, 17, 16, 15, 14, 13, 12, 11])

In [12]:
arr = np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [13]:
arr[0]

array([1, 2, 3, 4, 5])

In [14]:
arr[1]

array([ 6,  7,  8,  9, 10])

In [15]:
arr[-1]

array([26, 27, 28, 29, 30])

In [17]:
arr[2,3]

np.int64(14)

In [18]:
arr[1]

array([ 6,  7,  8,  9, 10])

In [19]:
arr[2,3]

np.int64(14)

In [23]:
arr[::-1]

array([[26, 27, 28, 29, 30],
       [21, 22, 23, 24, 25],
       [16, 17, 18, 19, 20],
       [11, 12, 13, 14, 15],
       [ 6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5]])

In [24]:
arr[0:]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [27]:
slice =arr[0:2,1:3]
slice

array([[2, 3],
       [7, 8]])

In [33]:
slice_arr = arr[3:6, 3:5]
slice_arr

array([[19, 20],
       [24, 25],
       [29, 30]])

In [36]:
slice=arr[3:5,1:4]
slice

array([[17, 18, 19],
       [22, 23, 24]])

In [39]:
arr= np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [41]:
bool = arr%2 ==0
bool

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [43]:
arr = arr[bool]
arr

array([ 2,  4,  6,  8, 10])