In [1]:
import numpy as np

In [3]:
s = np.array([

[5, 3, 4, 6, 7, 8, 9, 1, 2], 
[6, 7, 2, 1, 9, 5, 3, 4, 8],
[1, 9, 8, 3, 4, 2, 5, 6, 7],

[8, 5, 9, 7, 6, 1, 4, 2, 3],
[4, 2, 6, 8, 5, 3, 7, 9, 1],
[7, 1, 3, 9, 2, 4, 8, 5, 6],

[9, 6, 1, 5, 3, 7, 2, 8, 4],
[2, 8, 7, 4, 1, 9, 6, 3, 5],
[3, 4, 5, 2, 8, 6, 1, 7, 9]

])



In [12]:
np.sum(s, axis =1)

array([45, 45, 45, 45, 45, 45, 45, 45, 45])

In [17]:
b = np.sum(s, axis =0)
for i in b:
    if i ==45:
        print("Row is valid")
        break
    else:
        print("Invalid Data")


Row is valid


In [18]:
c = np.sum(s, axis =1)
for i in c:
    if i ==45:
        print("column is valid")
        break
    else:
        print("Invalid Data")
        

column is valid


In [17]:
 f = sum(s[:3 ,:3])

NameError: name 's' is not defined

In [18]:
sum(f)

NameError: name 'f' is not defined

In [2]:
import numpy as np 

In [4]:
data = np.array([
    [18, 85, 78],  # Student 1
    [19, 92, 88],  # Student 2
    [17, 76, 95],  # Student 3
    [18, 65, 70],  # Student 4
    [20, 90, 85]   # Student 5
])

In [6]:
data.shape

(5, 3)

In [12]:
np.mean(data [: , 0])

np.float64(18.4)

In [26]:
a = data[0:5 , 1:2]
a

array([[85],
       [92],
       [76],
       [65],
       [90]])

In [27]:
np.sum(a)

np.int64(408)

In [28]:
b = data [:, 2 ]
b

array([78, 88, 95, 70, 85])

In [31]:
np.max(b)

np.int64(95)

In [32]:
a

array([[85],
       [92],
       [76],
       [65],
       [90]])

In [53]:
bool = data [:, 1 ]> 90
bool

array([False,  True, False, False, False])

In [55]:
arr = data[bool]
arr

array([[19, 92, 88]])

In [73]:
data[:, 1] += 5
data

array([[ 18, 115,  78],
       [ 19, 122,  88],
       [ 17, 106,  95],
       [ 18,  95,  70],
       [ 20, 120,  85]])

In [75]:
bool = data [ :, 0] < 19
bool

array([ True, False,  True,  True, False])

In [81]:
a= data[True]
a

array([[[ 18, 115,  78],
        [ 19, 122,  88],
        [ 17, 106,  95],
        [ 18,  95,  70],
        [ 20, 120,  85]]])

In [100]:
a = np.arange (9).reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [107]:
a[:3, :1]

array([[0],
       [3],
       [6]])